// Quick-commerce Flink-inspired palette: hot pink + dark navy
const colors = {
  light: {
    text: "#0A1B3D",
    tint: "#E2006A",
    background: "#FFFFFF",
    foreground: "#0A1B3D",
    heading: "#0A1B3D",
    card: "#FFFFFF",
    cardForeground: "#0A1B3D",
    primary: "#E2006A",
    primaryForeground: "#FFFFFF",
    primarySoft: "#FFE5F0",
    primarySoftForeground: "#E2006A",
    pinkBg: "#FFD9E8",
    secondary: "#F5F5F5",
    secondaryForeground: "#0A1B3D",
    muted: "#F5F5F5",
    mutedForeground: "#6B7280",
    accent: "#FFE5F0",
    accentForeground: "#B0004F",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#EBEBEB",
    input: "#EBEBEB",
    success: "#22C55E",
    warning: "#F59E0B",
  },
  dark: {
    text: "#F5F5F5",
    tint: "#FF1A85",
    background: "#0F0F0F",
    foreground: "#F5F5F5",
    heading: "#F5F5F5",
    card: "#171717",
    cardForeground: "#F5F5F5",
    primary: "#FF1A85",
    primaryForeground: "#FFFFFF",
    primarySoft: "#3D0E26",
    primarySoftForeground: "#FF6BB0",
    pinkBg: "#3D0E26",
    secondary: "#212121",
    secondaryForeground: "#F5F5F5",
    muted: "#1F1F1F",
    mutedForeground: "#9E9E9E",
    accent: "#3D0E26",
    accentForeground: "#FF6BB0",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#2A2A2A",
    input: "#2A2A2A",
    success: "#22C55E",
    warning: "#F59E0B",
  },
  radius: 14,
};

export default colors;
